services:
  jupyter-lab:
    build: .
    container_name: jupyterlab
    ports:
      - "8080:8080" # JupyterLab
    volumes:
      - "../code:/app/code:rw"
      - "../data:/app/data:rw"
      - "../logs:/app/logs:rw"
      - "../models:/app/models:rw"
    shm_size: '256gb' # increase or decrease shared memory
    post_start:
      - command: 'pip install -e "/app/code/deep-semantic-hashing/."'
    restart: always

    # uncomment for GPU support
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: all
    #          capabilities: [gpu]
